(() => {
  let financialCharges = [];
  let selectedChargeId = null;

  const financialStyle = document.createElement('style');
  financialStyle.textContent = `
    .fin2-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:18px}.fin2-head h2{margin:0 0 5px;color:var(--wine-dark);font:700 30px Georgia,serif}.fin2-head p{margin:0;color:var(--muted)}
    .fin2-actions{display:flex;gap:10px;flex-wrap:wrap}.fin2-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.fin2-card{padding:18px 20px;border-radius:18px;background:var(--surface-glass,var(--paper));border:1px solid rgba(255,255,255,.76);box-shadow:var(--shadow);backdrop-filter:blur(16px)}.fin2-card span{color:var(--muted);font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.fin2-card strong{display:block;margin-top:7px;color:var(--wine-dark);font-size:clamp(22px,2.5vw,30px)}.fin2-card.featured{color:white;background:linear-gradient(135deg,var(--wine-dark),var(--wine));border-color:transparent}.fin2-card.featured span,.fin2-card.featured strong{color:white}.fin2-card.danger strong{color:var(--red)}
    .fin2-toolbar{padding:18px 20px;display:flex;gap:12px;align-items:center;flex-wrap:wrap;border-bottom:1px solid var(--line)}.fin2-toolbar .search{min-width:220px;max-width:none}.fin2-filter{height:44px;padding:0 34px 0 12px;border:1px solid var(--line);border-radius:11px;background:white;color:var(--ink)}
    .fin2-table{min-width:980px}.fin2-name strong{display:block}.fin2-name small{color:var(--muted)}.fin2-status{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:999px;font-size:11px;font-weight:850}.fin2-status::before{content:"";width:7px;height:7px;border-radius:50%;background:currentColor}.fin2-paid{color:var(--green);background:#e6f4ec}.fin2-pending{color:#9a6b16;background:#fff5d8}.fin2-overdue{color:var(--red);background:#fbeae7}.fin2-cancelled{color:var(--muted);background:#eee9e5}.fin2-actions-cell{display:flex;gap:6px;white-space:nowrap}.fin2-link{border:0;background:transparent;color:var(--wine);font-size:12px;font-weight:800;padding:6px}.fin2-empty{text-align:center;padding:50px 20px!important;color:var(--muted)}
    .fin2-modal-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.fin2-wide{grid-column:1/-1}.fin2-summary{padding:14px;border:1px solid var(--line);border-radius:13px;background:#faf7f2}.fin2-summary strong{display:block;color:var(--wine-dark)}.fin2-summary small{color:var(--muted)}
    @media(max-width:900px){.fin2-stats{grid-template-columns:1fr 1fr}.fin2-head{align-items:stretch;flex-direction:column}}@media(max-width:600px){.fin2-stats{grid-template-columns:1fr}.fin2-actions{display:grid;grid-template-columns:1fr}.fin2-actions .btn{width:100%}.fin2-toolbar{align-items:stretch;flex-direction:column}.fin2-toolbar>*{width:100%!important}.fin2-modal-grid{grid-template-columns:1fr}.fin2-wide{grid-column:auto}}
  `;
  document.head.appendChild(financialStyle);

  const financialView = document.getElementById('financialView');
  financialView.innerHTML = `<div class="fin2-head"><div><h2>Controle financeiro</h2><p>Gerencie cobranças, vencimentos, pagamentos e inadimplência.</p></div><div class="fin2-actions"><button type="button" class="btn btn-primary" id="fin2NewCharge">＋ Nova cobrança</button></div></div><section class="fin2-stats"><article class="fin2-card featured"><span>Recebido</span><strong id="fin2Received">R$ 0,00</strong></article><article class="fin2-card"><span>A receber</span><strong id="fin2Receivable">R$ 0,00</strong></article><article class="fin2-card danger"><span>Em atraso</span><strong id="fin2Overdue">R$ 0,00</strong></article><article class="fin2-card"><span>Cobranças abertas</span><strong id="fin2OpenCount">0</strong></article></section><section class="panel"><div class="fin2-toolbar"><div class="search"><input id="fin2Search" type="search" placeholder="Buscar aluno ou cobrança..."></div><select id="financialClassFilter" class="fin2-filter"><option value="all">Todas as turmas</option><option value="none">Sem turma</option></select><select id="fin2Status" class="fin2-filter"><option value="all">Todos os status</option><option value="paid">Pagos</option><option value="pending">Pendentes</option><option value="overdue">Atrasados</option><option value="cancelled">Cancelados</option></select><select id="fin2Type" class="fin2-filter"><option value="all">Todos os tipos</option><option value="entry">Inscrição</option><option value="monthly">Mensalidade</option><option value="other">Outros</option></select></div><div class="table-wrap"><table class="fin2-table"><thead><tr><th>Aluno</th><th>Turma</th><th>Cobrança</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Pagamento</th><th>Ações</th></tr></thead><tbody id="fin2List"></tbody></table></div></section>`;

  document.getElementById('appView').insertAdjacentHTML('beforeend', `<dialog id="fin2ChargeModal"><div class="modal-head"><div><h2 id="fin2ChargeTitle">Nova cobrança</h2><p>Cadastre valor, competência e vencimento.</p></div><button class="close" type="button" id="fin2ChargeClose">×</button></div><form id="fin2ChargeForm"><input type="hidden" id="fin2ChargeId"><div class="fin2-modal-grid"><div class="field fin2-wide"><label for="fin2Person">Aluno</label><select id="fin2Person" required></select></div><div class="field"><label for="fin2ChargeType">Tipo</label><select id="fin2ChargeType"><option value="monthly">Mensalidade</option><option value="entry">Inscrição</option><option value="other">Outro</option></select></div><div class="field"><label for="fin2Amount">Valor</label><input id="fin2Amount" type="number" min="0" step="0.01" required></div><div class="field"><label for="fin2Competence">Competência</label><input id="fin2Competence" placeholder="Ex.: Setembro/2026"></div><div class="field"><label for="fin2DueDate">Vencimento</label><input id="fin2DueDate" type="date"></div><div class="field fin2-wide"><label for="fin2Description">Descrição</label><input id="fin2Description" placeholder="Ex.: Mensalidade de setembro"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" id="fin2ChargeCancel">Cancelar</button><button class="btn btn-primary" type="submit">Salvar cobrança</button></div></form></dialog><dialog id="fin2PayModal"><div class="modal-head"><div><h2>Registrar pagamento</h2><p>Guarde os detalhes do recebimento.</p></div><button class="close" type="button" id="fin2PayClose">×</button></div><form id="fin2PayForm"><div class="fin2-summary" id="fin2PaySummary"></div><div class="fin2-modal-grid" style="margin-top:16px"><div class="field"><label for="fin2PaidAmount">Valor recebido</label><input id="fin2PaidAmount" type="number" min="0" step="0.01" required></div><div class="field"><label for="fin2PaidDate">Data do pagamento</label><input id="fin2PaidDate" type="date" required></div><div class="field fin2-wide"><label for="fin2PaymentMethod">Forma de pagamento</label><select id="fin2PaymentMethod"><option value="pix">PIX</option><option value="dinheiro">Dinheiro</option><option value="cartao">Cartão</option><option value="transferencia">Transferência</option><option value="outro">Outro</option></select></div><div class="field fin2-wide"><label for="fin2PayNotes">Observação</label><input id="fin2PayNotes" placeholder="Opcional"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" id="fin2PayCancel">Cancelar</button><button class="btn btn-primary" type="submit">Confirmar pagamento</button></div></form></dialog>`);

  const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const localDate=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'Sem vencimento';
  const studentById=id=>couples.find(c=>c.id===id);
  const personName=c=>{const s=studentById(c.student_id);return !s?'Aluno removido':c.person_slot==='person2'?(s.person2||s.person1):s.person1};
  const derivedStatus=c=>c.status==='paid'?'paid':c.status==='cancelled'?'cancelled':c.due_date&&c.due_date<todayISO()?'overdue':'pending';
  const statusLabel=s=>({paid:'Pago',pending:'Pendente',overdue:'Atrasado',cancelled:'Cancelado'}[s]||s);
  const typeLabel=t=>({entry:'Inscrição',monthly:'Mensalidade',other:'Outro'}[t]||t);
  const methodLabel=m=>({pix:'PIX',dinheiro:'Dinheiro',cartao:'Cartão',transferencia:'Transferência',outro:'Outro'}[m]||m||'—');

  function populateClassFilter(){const el=document.getElementById('financialClassFilter'),cur=el.value||'all';el.innerHTML=`<option value="all">Todas as turmas</option><option value="none">Sem turma</option>${classes.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}`;if([...el.options].some(o=>o.value===cur))el.value=cur}
  function populatePeople(selected=''){const el=document.getElementById('fin2Person');el.innerHTML=couples.flatMap(c=>[`<option value="${c.id}|person1">${escapeHtml(c.person1)}</option>`,...(c.person2?[`<option value="${c.id}|person2">${escapeHtml(c.person2)}</option>`]:[])]).join('')||'<option value="">Nenhum aluno cadastrado</option>';if(selected&&[...el.options].some(o=>o.value===selected))el.value=selected}

  async function loadFinancialCharges(){if(!currentUser)return;const {data,error}=await db.from('financial_charges').select('*').order('created_at',{ascending:false});if(error){console.error(error);toast('Erro ao carregar o financeiro.');return}financialCharges=data||[];renderFinancialV2()}
  function renderFinancialV2(){populateClassFilter();const cf=document.getElementById('financialClassFilter').value,sf=document.getElementById('fin2Status').value,tf=document.getElementById('fin2Type').value,q=document.getElementById('fin2Search').value.trim().toLowerCase();const matchesClass=c=>{const s=studentById(c.student_id),cid=s?.classId||'';return cf==='all'||(cf==='none'?!cid:cid===cf)};const filtered=financialCharges.filter(c=>matchesClass(c)&&(sf==='all'||derivedStatus(c)===sf)&&(tf==='all'||c.charge_type===tf)&&(!q||`${personName(c)} ${c.description||''} ${c.competence||''}`.toLowerCase().includes(q)));const base=financialCharges.filter(matchesClass),received=base.filter(c=>c.status==='paid').reduce((n,c)=>n+Number(c.paid_amount??c.amount??0),0),open=base.filter(c=>c.status==='pending'),receivable=open.reduce((n,c)=>n+Number(c.amount||0),0),overdue=open.filter(c=>derivedStatus(c)==='overdue').reduce((n,c)=>n+Number(c.amount||0),0);document.getElementById('fin2Received').textContent=money(received);document.getElementById('fin2Receivable').textContent=money(receivable);document.getElementById('fin2Overdue').textContent=money(overdue);document.getElementById('fin2OpenCount').textContent=open.length;document.getElementById('fin2List').innerHTML=filtered.length?filtered.map(c=>{const s=studentById(c.student_id),cl=s?classById(s.classId):null,st=derivedStatus(c),paid=c.status==='paid'?`<strong>${money(c.paid_amount??c.amount)}</strong><small>${c.paid_at?new Date(c.paid_at).toLocaleDateString('pt-BR'):'Data não informada'} • ${escapeHtml(methodLabel(c.payment_method))}</small>`:'<span>—</span>';return `<tr><td class="fin2-name"><strong>${escapeHtml(personName(c))}</strong><small>${c.person_slot==='person2'?'2ª pessoa':'1ª pessoa'}</small></td><td><span class="class-name">${cl?escapeHtml(cl.name):'Sem turma'}</span></td><td class="fin2-name"><strong>${escapeHtml(c.description||typeLabel(c.charge_type))}</strong><small>${escapeHtml(c.competence||typeLabel(c.charge_type))}</small></td><td><strong>${money(c.amount)}</strong></td><td>${localDate(c.due_date)}</td><td><span class="fin2-status fin2-${st}">${statusLabel(st)}</span></td><td class="fin2-name">${paid}</td><td><div class="fin2-actions-cell">${c.status==='pending'?`<button class="fin2-link" data-pay-charge="${c.id}">Receber</button>`:''}<button class="fin2-link" data-edit-charge="${c.id}">Editar</button></div></td></tr>`}).join(''):'<tr><td colspan="8" class="fin2-empty"><b>Nenhuma cobrança encontrada</b><br>Altere os filtros ou crie uma nova cobrança.</td></tr>'}

  function openChargeModal(c=null){selectedChargeId=c?.id||null;document.getElementById('fin2ChargeForm').reset();document.getElementById('fin2ChargeId').value=selectedChargeId||'';document.getElementById('fin2ChargeTitle').textContent=c?'Editar cobrança':'Nova cobrança';populatePeople(c?`${c.student_id}|${c.person_slot}`:'');document.getElementById('fin2Person').disabled=Boolean(c);if(c){document.getElementById('fin2ChargeType').value=c.charge_type;document.getElementById('fin2Amount').value=c.amount;document.getElementById('fin2Competence').value=c.competence||'';document.getElementById('fin2DueDate').value=c.due_date||'';document.getElementById('fin2Description').value=c.description||''}openDialog(document.getElementById('fin2ChargeModal'))}
  function openPayModal(c){selectedChargeId=c.id;document.getElementById('fin2PayForm').reset();document.getElementById('fin2PaidAmount').value=Number(c.amount||0).toFixed(2);document.getElementById('fin2PaidDate').value=todayISO();document.getElementById('fin2PaySummary').innerHTML=`<strong>${escapeHtml(personName(c))} — ${escapeHtml(c.description||typeLabel(c.charge_type))}</strong><small>${money(c.amount)}${c.due_date?` • vence ${localDate(c.due_date)}`:''}</small>`;openDialog(document.getElementById('fin2PayModal'))}
  async function syncLegacy(c,paid){if(c.source!=='legacy')return;const s=studentById(c.student_id);if(!s)return;if(c.charge_type==='entry'){const ep={...s.entryPayments,[c.person_slot]:paid};await db.from('students').update({entry_payments:ep,entry_paid:ep.person1||ep.person2}).eq('id',s.id);s.entryPayments=ep}else if(c.charge_type==='monthly'&&c.installment_number){const p=structuredClone(s.payments);p[c.person_slot][c.installment_number-1]=paid;await db.from('students').update({payments:p}).eq('id',s.id);s.payments=p}}

  document.getElementById('fin2ChargeForm').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('fin2ChargeId').value,[student_id,person_slot]=document.getElementById('fin2Person').value.split('|'),payload={charge_type:document.getElementById('fin2ChargeType').value,amount:Math.max(0,Number(document.getElementById('fin2Amount').value)||0),competence:document.getElementById('fin2Competence').value.trim(),description:document.getElementById('fin2Description').value.trim(),due_date:document.getElementById('fin2DueDate').value||null};const r=id?await db.from('financial_charges').update(payload).eq('id',id).select().single():await db.from('financial_charges').insert({...payload,student_id,person_slot,source:'manual'}).select().single();if(r.error)return toast('Não foi possível salvar a cobrança.');financialCharges=id?financialCharges.map(c=>c.id===id?r.data:c):[r.data,...financialCharges];closeDialog(document.getElementById('fin2ChargeModal'));renderFinancialV2();toast('Cobrança salva!')});
  document.getElementById('fin2PayForm').addEventListener('submit',async e=>{e.preventDefault();const c=financialCharges.find(x=>x.id===selectedChargeId);if(!c)return;const d=document.getElementById('fin2PaidDate').value,payload={status:'paid',paid_amount:Math.max(0,Number(document.getElementById('fin2PaidAmount').value)||0),paid_at:d?`${d}T12:00:00`:new Date().toISOString(),payment_method:document.getElementById('fin2PaymentMethod').value,notes:document.getElementById('fin2PayNotes').value.trim()},{data,error}=await db.from('financial_charges').update(payload).eq('id',c.id).select().single();if(error)return toast('Não foi possível registrar o pagamento.');await syncLegacy(c,true);financialCharges=financialCharges.map(x=>x.id===c.id?data:x);closeDialog(document.getElementById('fin2PayModal'));renderFinancialV2();if(typeof render==='function')render();toast('Pagamento registrado!')});
  document.getElementById('fin2List').addEventListener('click',e=>{const p=e.target.closest('[data-pay-charge]'),ed=e.target.closest('[data-edit-charge]');if(p)openPayModal(financialCharges.find(c=>c.id===p.dataset.payCharge));if(ed)openChargeModal(financialCharges.find(c=>c.id===ed.dataset.editCharge))});
  ['fin2Search','financialClassFilter','fin2Status','fin2Type'].forEach(id=>{const el=document.getElementById(id);el.addEventListener(id==='fin2Search'?'input':'change',renderFinancialV2)});document.getElementById('fin2NewCharge').onclick=()=>openChargeModal();document.getElementById('fin2ChargeClose').onclick=document.getElementById('fin2ChargeCancel').onclick=()=>closeDialog(document.getElementById('fin2ChargeModal'));document.getElementById('fin2PayClose').onclick=document.getElementById('fin2PayCancel').onclick=()=>closeDialog(document.getElementById('fin2PayModal'));
  const oldLoadData=loadData;loadData=async function(){await oldLoadData();await loadFinancialCharges()};const oldSetView=setView;setView=function(view){oldSetView(view);if(view==='financial')loadFinancialCharges()};
  window.loadFinancialCharges=loadFinancialCharges;window.renderFinancialV2=renderFinancialV2;
})();